name: CD

on:
  release:
    types: [ published ]
jobs:
  build:
    if: github.event.head_commit.committer.name != 'Versioning Action'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - uses: tool3/bump@master
        id: bump
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          user: 'Versioning Action'
          email: 'versioning@github.com'
          branch: 'main'
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install dependencies
        run: |
          npm install
      - name: Compile
        run: |
          npm run compile
      - name: Package VSIX
        run: |
          npm run package
      - name: Publish VSIX
        run: |
          npx vsce publish --packagePath ./release.vsix --pat ${{ secrets.VSCE_PAT }}
        if: secrets.VSCE_PAT != null