name: CD

on:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: auth0-vscode
      - name: Publish VSIX
        run: |
          npx vsce publish --packagePath ./release.vsix --pat ${{ secrets.VSCE_PAT }}
        if: secrets.VSCE_PAT != null