name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
    - created
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install Dependencies
      run: npm install
    - name: Run Lint
      run: npm run lint
    - name: Run Tests (macOS & Windows)
      run: npm run test
      if: runner.os != 'Linux'
    - name: Run Tests (Linux)
      run: xvfb-run -a npm run test
      if: runner.os == 'Linux'
    - name: Build Production
      run: npm run build:production
      if: runner.os == 'Linux'
    - name: Package VSIX
      run: npm run package
      if: runner.os == 'Linux'
    - name: Upload Artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2
      with:
        name: test-vscode
        path: release.vsix
    - name: Publish Artifact
      if: success() && startsWith( github.ref, 'refs/tags/releases/') && matrix.os == 'ubuntu-latest'
      run: npm run deploy
      env:
        VSCE_PAT: ${{secrets.VSCE_PAT}}