name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    if: github.event.head_commit.committer.name != 'Versioning Action'
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: 10.x
    - name: Install Dependencies
      run: npm install
    - name: Run Lint
      run: npm run lint
    - name: Run Test
      run: npm run compile
    - name: Package VSIX
      run: npm run package
